// 错误码常量（ESM）
export default {
  PROJECT_STARTING: "PROJECT_STARTING",
  INVALID_SCRIPT_TYPE: "INVALID_SCRIPT_TYPE",
  SYNTAX_CHECK_FAILED: "SYNTAX_CHECK_FAILED",
  DEV_SERVER_START_FAILED: "DEV_SERVER_START_FAILED",
};
